services:
  - type: web
    name: discord-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISCORD_TOKEN
        sync: false
      - key: DASHBOARD_SECRET_KEY
        sync: false
      - key: ADMIN_CODE
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true 